customhost = "employee.cyqu1vg9nqwl.us-east-1.rds.amazonaws.com"
customuser = "admin"
custompass = "rEnI:lR!dC(1YeR|>wIX|Nt4?nQD"
customdb = "employee"
custombucket = "leongyy-employee"
customregion = "us-east-1"
